load("//third_party/qt5:qt.bzl", "qt_cc_library")

package(default_visibility = ["//visibility:public"])

qt_cc_library(
    name = "btviz_resource_lib",
    srcs = glob([
    ]),
    hdrs = glob([
    ]),
    copts = [
        "-Iexternal/qt",
    ],
    includes = [
    ],
    linkstatic = False,
    res = [
        "resource.qrc",
    ],
    uis = [
    ],
    deps = [
        "@qt//:qt_core",
        "@qt//:qt_gui",
        "@qt//:qt_opengl",
        "@qt//:qt_widgets",
    ],
)