package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "my_planner",
    srcs = ["main.cc"],
    deps = [
        "//my_cpp/planner/lib:my_planner_lib",
        "//cyber",
    ],
)
