package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "talker_cc_proto",
    deps = [
        ":talker_proto",
    ],
)

proto_library(
    name = "talker_proto",
    srcs = [
        "talker.proto",
    ],
)
