package(default_visibility = ["//visibility:public"])

cc_library(
    name = "my_planning_gflags",
    srcs = [
        "my_planning_gflags.cc",
    ],
    hdrs = [
        "my_planning_gflags.h",
    ],
    deps = [
        "//external:gflags",
    ],
)