package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "talker",
    srcs = ["talker.cc"],
    deps = [
        "//cyber",
        "//my_cpp/talker/proto:talker_cc_proto",
    ],
)
